name: test-update-db

on:
  push:
    branches:
      - main

jobs:
  update-db:
    runs-on: windows-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@main
      
      #- name: List repository files
      #  shell: pwsh
      #  run: |
      #    Get-ChildItem -Recurse -Depth 4 | Select-Object FullName
      
      - name: Run EXE from specific folder
        shell: pwsh
        run: |
          $exePath = Join-Path $env:GITHUB_WORKSPACE "Tools\FFmpeg\ffmpeg.exe"
          if (-not (Test-Path $exePath)) {
            throw "EXE not found at: $exePath"
          }
          
          & $exePath -h
          